[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Yahor Poresh"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4.0.0-beta.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
